---
selfSigned:
  create: true
  image: gcr.io/google_containers/kubernetes-dashboard-init-amd64
  imageTag: "v1.0.0"
  imagePullPolicy: "IfNotPresent"
  caDays: 10000
  certDays: 10000
  altNames:
  - dex.k8s.expllore.me.uk
  altIPs: {}
#  - 192.168.42.219

secret: {}
#  Override the default secret names here.
#  tlsName: dex-tls
#  caName: dex-ca

config:
  issuer: https://dex.k8s.expllore.me.uk:5556
  storage:
    type: kubernetes
    config:
      inCluster: true
  logger:
    level: debug
  web:
    https: 0.0.0.0:5556
    tlsCert: /etc/dex/tls/tls.crt
    tlsKey: /etc/dex/tls/tls.key
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: 4c03a29103468c63877a
      clientSecret: 11a2a1b5978dbd5927bbedb4e24bc4ae057f3105
      redirectURI: https://dex.k8s.expllore.me.uk:5556/callback
      org: kubernetes
  oauth2:
    skipApprovalScreen: true

  enablePasswordDB: true
  staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

