apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    email: aleksey.ponomaryov@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory

