---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/nfs
  claimRef:
    namespace: kube-system
    name: data-nfs-storage-nfs-server-provisioner-0

